version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: notatkomator-postgress
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notatkomator
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_network
      
  adminer:
    image: adminer
    container_name: notatkomator-adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - dev_network

volumes:
  pgdata:

networks:
  dev_network:
    driver: bridge