version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: notatkomator-postgress
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notatkomator
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: notatkomator-admin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
