version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: notatkomator-postgress
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_network

  adminer:
    image: adminer
    container_name: notatkomator-adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - dev_network

volumes:
  pgdata:

networks:
  dev_network:
    driver: bridge
